# Site settings
title: DEEPAK MAHTANI
description: WELCOME TO MY DIGITAL WORLD OF DATA!
repository: deepakm925/deepakm925.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://deepakm925.github.io"
author: DeepakMahtani
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
